### ISSUE TITLE
space group origin number 

### ISSUE THREAD

**Issue by chdashtyj** [stefsmeets/focus_package#8]
hello everyone:
I have used FOCUS for a while, recetly some littile problems distrub me.
When I sovle a zeolite structure with space group Pmmn (with two origins), the output file cannot
be converted to cif.file and cannot used in KRIBER either. 
The error list said: RuntimeError: Fw0000  -> KRIBER ERROR space group PMMN:2
not found => P1 
I donot know what this means
Anyone please help me, Thank you very much.

**Comment by chdashtyj** [comment]
The detail error message like this:
 File "C:\Python27-32\lib\runpy.py", line 174, in _run_module_as_main
  File "C:\Python27-32\lib\runpy.py", line 72, in _run_code
  File "D:\refinement\focus-package-win\fo2cif.exe\__main__.py", line 10, in <module>
  File "D:\refinement\focus-package-win\Lib/site-packages\focus_tools\focus_tools.py", line 312, in fo2cif_entry
    pykriber.strudat2cif()
  File "D:\refinement\focus-package-win\Lib/site-packages\focus_tools\pykriber.py", line 91, in strudat2cif
    raise RuntimeError("{}  ->  KRIBER {}".format(key, line))
RuntimeError: Fw0000  ->  KRIBER  ERROR  space group PMMN:2                         not found => P1

**Comment by stefsmeets** [comment]
Hi @chdashtyj, it means that Kriber cannot find the space group `PMMN:2`, so the program uses `P1` as a fallback. I checked the manual for Kriber ([see here](https://github.com/stefsmeets/focus_package/blob/master/manuals/kriber/input_manual.txt#L61)), and to specify the 2nd origin choice the right syntax is to append `S` (instead of `:2`), i.e. `PMMNS`. So it seems like something goes wrong with the file conversion here, I will have a look at it. But as a work-around, you can change the entries in your `strudat` file instead, and run `fo2strudat` and `strudat2cif` separately.

**Comment by chdashtyj** [comment]
Thank you for your kind help. I edit the output file changing space group PMMN:2 to PMMNS and then everything worked.
